import Header from '../components/Header'
import Footer from '../components/Footer'

export default function TermsPage() {
  return (
    <>
      <Header />
      <main style={{ paddingTop: 96 }}>
        <div className="container-narrow section">
          <h1 style={{ fontSize: '2.5rem', marginBottom: '0.5rem' }}>Terms of Service</h1>
          <p style={{
            color: 'var(--danger)', fontSize: '0.875rem', fontWeight: 500,
            marginBottom: '2rem', padding: '0.75rem 1rem',
            background: 'rgba(220,120,100,0.08)', borderRadius: 'var(--radius-sm)',
            border: '1px solid rgba(220,120,100,0.2)',
          }}>
            ⚠️ DRAFT — This is placeholder text and does not constitute a binding agreement. Finalised terms will be published before public launch.
          </p>

          <div style={{ color: 'var(--text-secondary)', lineHeight: 1.8, fontSize: '0.9375rem' }}>
            <p style={{ marginBottom: '1rem' }}>
              <strong style={{ color: 'var(--text)' }}>Last updated:</strong> {new Date().toLocaleDateString('en-GB', { day: 'numeric', month: 'long', year: 'numeric' })}
            </p>

            <h2 style={{ fontSize: '1.25rem', marginTop: '2rem', marginBottom: '0.75rem' }}>1. Service description</h2>
            <p style={{ marginBottom: '1rem' }}>
              Revise OS ("the Service") is an AI-powered adaptive study platform that helps users create, organise, and review revision materials. The Service includes features such as flashcard generation, quiz creation, knowledge graphs, and spaced repetition scheduling.
            </p>

            <h2 style={{ fontSize: '1.25rem', marginTop: '2rem', marginBottom: '0.75rem' }}>2. Account registration</h2>
            <p style={{ marginBottom: '1rem' }}>
              You may register using Google Sign-In. You are responsible for maintaining the security of your account. You must provide accurate information during registration. [Placeholder: age restrictions and eligibility requirements will be specified here.]
            </p>

            <h2 style={{ fontSize: '1.25rem', marginTop: '2rem', marginBottom: '0.75rem' }}>3. Acceptable use</h2>
            <p style={{ marginBottom: '1rem' }}>
              You agree not to upload illegal, harmful, or copyrighted content without rights. The Service is intended for personal educational use. [Placeholder: detailed acceptable use policy will be provided.]
            </p>

            <h2 style={{ fontSize: '1.25rem', marginTop: '2rem', marginBottom: '0.75rem' }}>4. Your content</h2>
            <p style={{ marginBottom: '1rem' }}>
              You retain ownership of all materials you upload. By uploading, you grant Revise OS a limited licence to process your content solely for the purpose of providing the Service. We do not claim ownership of your study materials.
            </p>

            <h2 style={{ fontSize: '1.25rem', marginTop: '2rem', marginBottom: '0.75rem' }}>5. AI-generated content</h2>
            <p style={{ marginBottom: '1rem' }}>
              Flashcards, quiz questions, and other content generated by the Service are produced by AI models and may contain errors. The Service is a study aid and should not be relied upon as the sole source of information. Always verify important facts with authoritative sources.
            </p>

            <h2 style={{ fontSize: '1.25rem', marginTop: '2rem', marginBottom: '0.75rem' }}>6. Limitation of liability</h2>
            <p style={{ marginBottom: '1rem' }}>
              The Service is provided "as is" without warranty. [Placeholder: complete limitation of liability and indemnification terms to be drafted by legal counsel.]
            </p>

            <h2 style={{ fontSize: '1.25rem', marginTop: '2rem', marginBottom: '0.75rem' }}>7. Changes to terms</h2>
            <p style={{ marginBottom: '1rem' }}>
              We may update these terms from time to time. We will notify registered users of material changes. [Placeholder: notification mechanism details.]
            </p>

            <h2 style={{ fontSize: '1.25rem', marginTop: '2rem', marginBottom: '0.75rem' }}>8. Contact</h2>
            <p style={{ marginBottom: '1rem' }}>
              For questions about these terms, contact <strong style={{ color: 'var(--text)' }}>hello@reviseos.co.uk</strong>. [Placeholder: registered company details to be added.]
            </p>
          </div>
        </div>
      </main>
      <Footer />
    </>
  )
}
