"""add user scoped schema fields

Revision ID: 609db23bfda9
Revises: 9c5c1fb675a6
Create Date: 2026-04-10 22:16:50.047147

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '609db23bfda9'
down_revision: Union[str, None] = '9c5c1fb675a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('concepts', sa.Column('user_id', sa.String(length=36), nullable=True))
    op.add_column('concepts', sa.Column('source_document_ids', sa.Text(), nullable=True))
    op.add_column('concepts', sa.Column('related_concept_ids', sa.Text(), nullable=True))
    op.add_column('concepts', sa.Column('embedding', sa.Text(), nullable=True))
    op.create_index(op.f('ix_concepts_user_id'), 'concepts', ['user_id'], unique=False)
    op.create_foreign_key(None, 'concepts', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.add_column('documents', sa.Column('user_id', sa.String(length=36), nullable=True))
    op.add_column('documents', sa.Column('transcript', sa.Text(), nullable=True))
    op.add_column('documents', sa.Column('slide_count', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_documents_user_id'), 'documents', ['user_id'], unique=False)
    op.create_foreign_key(None, 'documents', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.add_column('flashcards', sa.Column('user_id', sa.String(length=36), nullable=True))
    op.create_index(op.f('ix_flashcards_user_id'), 'flashcards', ['user_id'], unique=False)
    op.create_foreign_key(None, 'flashcards', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.add_column('modules', sa.Column('user_id', sa.String(length=36), nullable=True))
    op.create_index(op.f('ix_modules_user_id'), 'modules', ['user_id'], unique=False)
    op.create_foreign_key(None, 'modules', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.add_column('quiz_questions', sa.Column('user_id', sa.String(length=36), nullable=True))
    op.create_index(op.f('ix_quiz_questions_user_id'), 'quiz_questions', ['user_id'], unique=False)
    op.create_foreign_key(None, 'quiz_questions', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.add_column('review_logs', sa.Column('user_id', sa.String(length=36), nullable=True))
    op.create_index(op.f('ix_review_logs_user_id'), 'review_logs', ['user_id'], unique=False)
    op.create_foreign_key(None, 'review_logs', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.add_column('study_sessions', sa.Column('user_id', sa.String(length=36), nullable=True))
    op.create_index(op.f('ix_study_sessions_user_id'), 'study_sessions', ['user_id'], unique=False)
    op.create_foreign_key(None, 'study_sessions', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'study_sessions', type_='foreignkey')
    op.drop_index(op.f('ix_study_sessions_user_id'), table_name='study_sessions')
    op.drop_column('study_sessions', 'user_id')
    op.drop_constraint(None, 'review_logs', type_='foreignkey')
    op.drop_index(op.f('ix_review_logs_user_id'), table_name='review_logs')
    op.drop_column('review_logs', 'user_id')
    op.drop_constraint(None, 'quiz_questions', type_='foreignkey')
    op.drop_index(op.f('ix_quiz_questions_user_id'), table_name='quiz_questions')
    op.drop_column('quiz_questions', 'user_id')
    op.drop_constraint(None, 'modules', type_='foreignkey')
    op.drop_index(op.f('ix_modules_user_id'), table_name='modules')
    op.drop_column('modules', 'user_id')
    op.drop_constraint(None, 'flashcards', type_='foreignkey')
    op.drop_index(op.f('ix_flashcards_user_id'), table_name='flashcards')
    op.drop_column('flashcards', 'user_id')
    op.drop_constraint(None, 'documents', type_='foreignkey')
    op.drop_index(op.f('ix_documents_user_id'), table_name='documents')
    op.drop_column('documents', 'slide_count')
    op.drop_column('documents', 'transcript')
    op.drop_column('documents', 'user_id')
    op.drop_constraint(None, 'concepts', type_='foreignkey')
    op.drop_index(op.f('ix_concepts_user_id'), table_name='concepts')
    op.drop_column('concepts', 'embedding')
    op.drop_column('concepts', 'related_concept_ids')
    op.drop_column('concepts', 'source_document_ids')
    op.drop_column('concepts', 'user_id')
    # ### end Alembic commands ###
